#!/bin/bash

set -e
set -x

STAGING=/opt/omegaup-staging
JS_DIST=frontend/www/js/dist/
YARN=node_modules/yarn/bin/yarn

# Compile Vue files. This complicated version is needed to ensure that the
# correct environment is set.
sudo -u omegaup-www -i /bin/bash -c \
	"set -e;
   cd \"${STAGING}\";
   . /opt/nvm/nvm.sh;
   if [ \$(nvm current) = \"none\" ]; then
     nvm install node;
   fi;
   npm ls --parseable -g yarn > /dev/null || npm install -g yarn;
   yarn install;
   rm -rf \"${STAGING}/${JS_DIST}\";
   yarn run build"
